version: '3.9'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: senha123
      MARIADB_DATABASE: conversas_boot
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./dbdata:/var/lib/mysql

